{
  "@context": "https://openvex.dev/ns",
  "@id": "https://openvex.dev/docs/sysdig/vex-427ad2254b739b01dd993c09e805f7d0655638010e8522da97a20b2a96d9aed1",
  "author": "atomist/sysdig-integration@0.1.2",
  "role": "Document Creator",
  "version": "1",
  "statements": [
    {
      "vulnerability": "CVE-2019-12900",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/bzip2@1.0.6-r6?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2022-45143",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@9.0.55"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2021-43980",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@9.0.55",
        "pkg:maven/org.apache.tomcat.embed/tomcat-embed-websocket@9.0.55"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2201",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/libjpeg-turbo@1.5.3-r3?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-14498",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/libjpeg-turbo@1.5.3-r3?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-5094",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/e2fsprogs@1.44.2-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-5188",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/e2fsprogs@1.44.2-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-1000654",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/libtasn1@4.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-20217",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/krb5@1.15.3-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14578",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2803",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14593",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2978",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2981",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2805",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2698",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2945",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2992",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2949",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14556",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2659",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2602",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2757",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2987",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2842",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-11212",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-16435",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2988",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2989",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14803",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-3214",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2781",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2958",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14798",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14781",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14779",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2583",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-3139",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-3183",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-13785",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-3169",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14792",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2755",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2983",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14583",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2769",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-3149",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2964",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2745",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-3180",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2973",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2422",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2754",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14797",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2766",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2601",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2593",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2654",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-7317",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8",
        "pkg:alpine/libpng@1.6.34-r1?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2894",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2684",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2426",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2800",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2962",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2975",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2830",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14577",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2604",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2816",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2756",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14796",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14782",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14581",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2590",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2762",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-2773",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2999",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-3136",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2786",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14579",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2933",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-14621",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/openjdk8@8.181.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-20346",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-8457",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-11655",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-19242",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-19244",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-16168",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-14697",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/musl@1.1.19-r10?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-14550",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/libpng@1.6.34-r1?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-14048",
      "product": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:alpine/libpng@1.6.34-r1?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    }
  ]
}
