{
  "@context": "https://openvex.dev/ns",
  "@id": "https://openvex.dev/docs/sysdig/vex-427ad2254b739b01dd993c09e805f7d0655638010e8522da97a20b2a96d9aed1",
  "author": "atomist/sysdig-integration@0.1.5",
  "role": "Document Creator",
  "version": "1",
  "statements": [
    {
      "vulnerability": "CVE-2019-12900",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/bzip2@1.0.6-r6?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2022-45143",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@9.0.55"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2021-43980",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@9.0.55",
        "pkg:maven/org.apache.tomcat.embed/tomcat-embed-websocket@9.0.55"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-2201",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/libjpeg-turbo@1.5.3-r3?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-14498",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/libjpeg-turbo@1.5.3-r3?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-5094",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/e2fsprogs@1.44.2-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-5188",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/e2fsprogs@1.44.2-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-1000654",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/libtasn1@4.13-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-20217",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/krb5@1.15.3-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-20346",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-8457",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2020-11655",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-19242",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-19244",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2019-16168",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/sqlite@3.24.0-r0?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-14550",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/libpng@1.6.34-r1?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    },
    {
      "vulnerability": "CVE-2018-14048",
      "products": [
        "pkg:docker/atomist/vulnapp@sha256:9c8a98c1f53866b3d8c121481424a78a9e9473334fd64ce29e7823dac9ea9c64"
      ],
      "subcomponents": [
        "pkg:apk/alpine/libpng@1.6.34-r1?os_name=alpine&os_version=3.8"
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "Vulnerable package not loaded at runtime"
    }
  ]
}
